version: "3.5"
services:
  pismo-transactions:
    hostname: pismo-transactions
    image: pismo-transactions:latest
    build:
      context: .
    restart: always
    ports:
      - '8080:8080'
    env_file:
      - .env
    depends_on:
      - mongodb
  mongodb:
    image: "mongo:4.0.19"
    environment:
      - MONGO_INITDB_DATABASE=account
      - MONGO_INITDB_ROOT_USERNAME=usercore
      - MONGO_INITDB_ROOT_PASSWORD=usercore
    ports:
      - "27017:27017"
    volumes:
      - ./db:/docker-entrypoint-initdb.d:ro